blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Nemesis533/Local_LLHAMA/discussions
    about: Ask questions and discuss ideas with the community
